### ISSUE TITLE
Adding a script to an entity with a public multidimensional array crashes editor.

### ISSUE THREAD

**Issue by westonmcnamara** [stride3d/xenko#645] opened 2020-04-02 18:17 UTC
**Release Type**: Official Release 

**Version**: 3.0.0.9

**Platform(s)**: Windows

**Describe the bug**
Adding a script with a public multidimensional array to an entity will crash the editor.

**To Reproduce**
1. Create a new sync script called test
2. Add `public int[,] grid = new int[1 ,1];` in the script.
3. Reload assemblies
4. Attach to an empty entity

**Expected behavior**
It should properly attach the script and display the array or throw an error or say that multidimensional arrays are not supported in the property grid.

**Screenshots**
If applicable, add screenshots to help explain your problem (use GitHub drag & drop)
![ss](https://user-images.githubusercontent.com/57050262/78283897-83c43800-74ec-11ea-9007-c12b538149d6.PNG)

**Additional context**
I'm not totally sure about the support of multidimensional arrays, but adding a script with a public one should not crash the editor, it should display a message.

**Comment by Eideren** [comment] 2020-04-02 18:26
Duplicate of #431

**Closed** 2020-04-04 09:13 UTC
Labels: bug
